		<ul class="nav nav-tabs nav-justified">
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
		    <li role="presentation" class="active"><a href="!#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Estado de cuenta</a></li>
		   
		   	<li role="presentation">
				<div class="input-group input-group-lg">
					<a href="../controllers/pagos/estadoCuenta" class="btn btn-default btn-lg">Imprimir</a>
				</div>
			</li>

		  </ul>
		  <!-- Tab panes -->
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane active">
			    	
	    		<table class="table table-striped" id="tablaCuenta">
		    		<tr>
		    			<th>Id</th>
		    			<th>Fecha</th>
		    			<th>Mes</th>
		    			<th>Apartamento</th>
		    			<th>Monto</th>   			
		    			<th>Cuenta</th>
		    		</tr>
		    		<?php for($i=0; $i<count($cxcAll); $i++){ $rs = $cxcAll[$i]; ?>
		    		<tr>
		    			<td><?php echo $rs['id_cxc']; ?></td>
		    			<td><?php echo $rs['fecha']; ?></td>
		    			<td><?php echo $rs['mes']; ?></td>
		    			<td><?php echo $rs['apto']; ?></td>
		    			<td class="monto"><?php echo "Bs. {$rs['monto']}"; ?></td>
		    			<td class="color">
		    				Bs. <span class="total"></span>
		    			</td>
		    		</tr> <?php } ?>
		    	</table>
		    </div>
		  </div><td></td>