<?php 
    $formaPago = new FormaPago();
    $formasPagos = $formaPago->getFormaPago();

    $instanciaBanco = new Banco();
    $bancos = $instanciaBanco->getBancos();

    $apartamento = new Apartamento();
    $apartamentos = $apartamento->getApartamentos();

    $mensualidad = new Mensualidad();
    $mensualidades = $mensualidad->getMensualidades();
?>
<div class="modal fade" id="pagarMensualidad">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Cancelación de mensualidad</h4>
            </div>
            <div class="modal-body">
                <!-- action="../controllers/notificacion/addNotificacion.php" method="post" -->
                <form id="formNuevoPagoMensualidad"> 
                   <input type="hidden" id="id_new_cxc">
                   <input type="hidden" id="new_fecha">
                   <input type="hidden" id="new_idApto">

                    <div class="form-group">
                        <select name="forma_pago" id="forma_pago_pagar" class="form-control">
                            <option value="">Selecciona una forma de pago</option>
                            <?php for($i=0; $i<count($formasPagos); $i++){ $rs = $formasPagos[$i]; ?>
                                <option value="<?php echo $rs['id_forma_pago']; ?>">
                                    <?php echo $rs['descripcion']; ?>        
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group">
                       <select name="banco" id="banco_pagar" class="form-control">
                            <option value="">Selecciona un banco</option>
                            <?php for($i=0; $i<count($bancos); $i++){ $rs = $bancos[$i]; ?>
                                <option value="<?php echo $rs['id_banco']; ?>">
                                    <?php echo $rs['descripcion']; ?>        
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" readonly="on" id="new_apto">
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" readonly="on" id="new_monto_pago">
                    </div>                   
<!--                     <div class="form-group">
                        <input class="form-control" type="text" onkeyup="subTotal(this);" id="monto" required placeholder="Monto a cancelar" autocomplete="off">
                    </div>                   
                    <div class="form-group">
                        <input class="form-control" type="text" name="total" id="total" readonly="off" placeholder="Total" autocomplete="off">
                    </div> -->
                    <div class="form-group">
                        <input class="form-control" type="text" id="referencia_pagar" name="referencia" required placeholder="Referencia" autocomplete="off">
                    </div> 
                    <div class="form-group">
                        <input class="form-control" type="text" id="descripcion_pagar" name="descripcion" required placeholder="Descripción" autocomplete="off">
                    </div> 
                    <div class="form-group">
                        <input class="form-control" type="date" id="fecha_pagar" name="fecha" required autocomplete="off">
                    </div>                    
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>