<div class="modal fade" id="nuevaFormaPago">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nuevo Formas de pago</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevaFormaPago" action="../controllers/formas_pago/addFormaPago.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="text" name="descripcion_forma_pago" id="descripcion_forma_pago" placeholder="Descripción" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>