<div id="form_container" ng-controller="usuariosctrl">
	<div class="col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 ">
		<div class="jumbotron">
			<div class="text-center">
				<img id="userLogo" src="public/images/user.png">
			</div>
			<div class="container">
				<form id="loginForm" class="form-group" onsubmit="login();">
				    <div class="form-group">
				        <input class="form-control input-lg" type="text" ng-model="user.usuario" name="usuario" id="usuario" autofocus placeholder="Usuario" autocomplete="off">
				    </div>
				    <div class="form-group">
				        <input class="form-control input-lg" type="password" ng-model="user.password" name="password" id="password" placeholder="Contraseña" autocomplete="off">
				    </div>
				    <input class="btn btn-primary btn-block input-lg" type="submit" value="Iniciar sesion">
				</form>
			</div>
		</div>
	</div>
</div>
<!-- action="controllers/usuarios/usuario.php" method="post" -->
<!-- onsubmit="login();" id="loginForm" -->