/*Tablas de Usuarios*/
CREATE TABLE niveles(
	id_nivel INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nivel VARCHAR(100) NOT NULL, #3 Propietario, #2 Administrador condiminio, #1 Administrador del sistema
	descripcion VARCHAR(100) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE usuarios(
	id_usuario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_nivel INT UNSIGNED NOT NULL,
	nombres VARCHAR(100) NOT NULL,
	apellidos VARCHAR(100) NOT NULL,
	correo VARCHAR(100) NOT NULL UNIQUE,
	contrasena VARCHAR(100) NOT NULL,
	telefono VARCHAR(100) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_nivel) REFERENCES niveles(id_nivel)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE alicuotas(
	id_alicuota INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	alicuota VARCHAR(100) NOT NULL,
	monto VARCHAR(100) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE apartamentos(
	id_apartamento INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_alicuota INT UNSIGNED NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	saldo VARCHAR(100) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_alicuota) REFERENCES alicuotas(id_alicuota)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE propietarios(
	id_propietario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	cedula VARCHAR(100) NOT NULL,
	nombres VARCHAR(100) NOT NULL,
	apellidos VARCHAR(100) NOT NULL,
	telefono VARCHAR(100) NOT NULL,
	correo VARCHAR(100) NOT NULL,
	notas VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE contrato(
	id_contrato INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_apartamento INT UNSIGNED NOT NULL,
	id_propietario INT UNSIGNED NOT NULL,
	fecha_inicio VARCHAR(25) NOT NULL,
	fecha_fin VARCHAR(25) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_apartamento) REFERENCES apartamentos(id_apartamento)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE proveedores(
	id_proveedor INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombres VARCHAR(100) NOT NULL,
	apellidos VARCHAR(100) NOT NULL,
	correo VARCHAR(100) NOT NULL,
	telefono VARCHAR(100) NOT NULL,
	notas VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE mensualidad(
	id_mensualidad INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	descripcion VARCHAR(255) NOT NULL,
	total VARCHAR(25) NOT NULL,
	fecha VARCHAR(25) NOT NULL,
	tipo TINYINT NULL DEFAULT 0,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE detalle_mensualidad(
	id_detalle_mensualidad INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_mensualidad INT UNSIGNED NOT NULL,
	id_gasto INT UNSIGNED NOT NULL,
	fecha VARCHAR(25) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_mensualidad) REFERENCES mensualidad(id_mensualidad)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE ut(
	id_ut INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ut VARCHAR(55) NOT NULL,
	anio INT(5) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE formas_pagos(
	id_forma_pago INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	descripcion VARCHAR(115) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE bancos(
	id_banco INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	descripcion VARCHAR(115) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE documentos(
	id_documento INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	fecha VARCHAR(25) NOT NULL,
	ubicacion VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE auditorias(
	id_auditoria INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT UNSIGNED NOT NULL,
	evento VARCHAR(25) NOT NULL,
	tabla VARCHAR(25) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE novedades(
	id_novedad INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT UNSIGNED NOT NULL,
	descripcion VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE gastos(
	id_gasto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_ut INT UNSIGNED NOT NULL,
	descripcion VARCHAR(255) NOT NULL,
	monto VARCHAR(25) NOT NULL,
	tipo TINYINT NULL DEFAULT 0,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_ut) REFERENCES ut(id_ut)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE detalle(
	id_detalle INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_gasto INT UNSIGNED NOT NULL,
	id_proveedor INT UNSIGNED NOT NULL,
	id_ut INT UNSIGNED NOT NULL,
	id_mensualidad INT UNSIGNED NOT NULL,
	monto VARCHAR(25) NOT NULL,
	tipo TINYINT NULL DEFAULT 0, /*1 Fijo 2 Variable*/
	descripcion VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_gasto) REFERENCES gastos(id_gasto)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE cxc(
	id_cxc INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_apartamento INT UNSIGNED NOT NULL,
	id_alicuota INT UNSIGNED NOT NULL,
	id_mensualidad INT UNSIGNED NOT NULL,
	monto VARCHAR(25) NOT NULL,
	cancelado INT UNSIGNED NOT NULL DEFAULT 0,
	fecha VARCHAR(25) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_apartamento) REFERENCES apartamentos(id_apartamento)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE pagos(
	id_pago INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_forma_pago INT UNSIGNED NOT NULL,
	id_apartamento INT UNSIGNED NOT NULL,
	id_banco INT UNSIGNED NOT NULL,
	id_usuario INT UNSIGNED NOT NULL,
	monto VARCHAR(25) NOT NULL,
	referencia VARCHAR(25) NOT NULL,
	aprobado TINYINT(1) NOT NULL DEFAULT 0,
	descripcion VARCHAR(255) NOT NULL,
	fecha VARCHAR(25) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_apartamento) REFERENCES apartamentos(id_apartamento)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE cxc_has_pago(
	id_cxc_has_pago INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_cxc INT UNSIGNED NOT NULL,
	cancelado INT UNSIGNED NOT NULL DEFAULT 0,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (id_cxc) REFERENCES cxc(id_cxc)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;