<div class="modal fade" id="editProveedor">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Proveedor</h4>
            </div>
            <div class="modal-body">
                <form id="formEditProveedor" action="../controllers/proveedores/editProveedor.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_proveedor" id="id_new_proveedor">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_nombres" id="new_nombres" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_apellidos" id="new_apellidos" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" name="new_correo" id="new_correo" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_notas" id="new_notas" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>