<div class="modal fade" id="nuevoProveedor">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nuevo Proveedor</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevoPro" action="../controllers/proveedores/addProveedor.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="text" name="nombres" required placeholder="Nombres" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="apellidos" required placeholder="Apellidos" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" name="correo" required placeholder="Correo" autocomplete="off">
                    </div>                    
                    <div class="form-group">
                        <input class="form-control" type="text" name="telefono" required placeholder="Telefono" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="notas" placeholder="Notas" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>