<?php 
    $ut = new Ut();
    $uts = $ut->getUt();
?>
<div class="modal fade" id="editGasto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar gasto</h4>
            </div>
            <div class="modal-body">
                <form id="formEditProveedor" action="../controllers/gastos/editGasto.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_gasto" id="id_new_gasto">
                    </div>
                    <div class="form-group">
                        <select name="id_new_ut_gasto" class="form-control">
                            <option value="">Selecciona una unidad tributaria</option>
                            <?php for($i=0; $i<count($uts); $i++){ $rs = $uts[$i]; ?>
                                <option value="<?php echo $rs['id_ut']; ?>">
                                    <?php echo $rs['ut']; ?>        
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_descripcion_gasto" id="new_descripcion_gasto" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" id="new_monto_gasto" onkeyup="subTotalGastoEdit(this);" autocomplete="off">
                        <input type="hidden" name="new_monto_gasto" id="newTotalGasto">
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            <select name="new_tipo_gasto" class="form-control">
                                <option value="">Selecciona un tipo</option>
                                <option value="1">Uno</option>
                                <option value="2">Dos</option>
                            </select>
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>