<!-- </div> -->
<script type="text/javascript" src="../public/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="../public/js/bootstrap.min.js"></script>
<!-- Scripts propios -->
<script type="text/javascript" src="../public/js/filtro.js"></script>
<script type="text/javascript" src="../public/js/utils.js"></script>
<!-- <script type="text/javascript" src="public/js/modulo.js"></script>
<script type="text/javascript" src="public/js/routes.js"></script> -->
<!-- Home -->
<!-- <script type="text/javascript" src="public/js/home/homectrl.js"></script> -->
<!-- Config -->
<!-- <script type="text/javascript" src="public/js/config/configctrl.js"></script> -->
<script type="text/javascript" src="../public/js/config/config.js"></script>
<!-- Ut -->
<!-- <script type="text/javascript" src="public/js/ut/utctrl.js"></script> -->
<script type="text/javascript" src="../public/js/ut/ut.js"></script>
<!-- Alicuotas -->
<!-- <script type="text/javascript" src="public/js/alicuotas/alicuotactrl.js"></script> -->
<script type="text/javascript" src="../public/js/alicuotas/alicuota.js"></script>
<!-- Formas de pago -->
<!-- <script type="text/javascript" src="public/js/formas_pagos/formasPagosCtrl.js"></script> -->
<script type="text/javascript" src="../public/js/formas_pagos/formas_pagos.js"></script>
<!-- Bancos -->
<!-- <script type="text/javascript" src="public/js/bancos/bancoctrl.js"></script> -->
<script type="text/javascript" src="../public/js/bancos/bancos.js"></script>
<!-- Usuarios -->
<script type="text/javascript" src="../public/js/usuarios/login.js"></script>
<!-- <script type="text/javascript" src="public/js/usuarios/usuarioctrl.js"></script> -->
<script type="text/javascript" src="../public/js/usuarios/usuarios.js"></script>
<script type="text/javascript" src="../public/js/usuarios/perfil.js"></script>
<!-- Auditorias -->
<!-- <script type="text/javascript" src="public/js/auditoria/auditoriactrl.js"></script> -->
<script type="text/javascript" src="../public/js/auditoria/auditoria.js"></script>
<script type="text/javascript" src="../public/js/novedad/novedad.js"></script>
<script type="text/javascript" src="../public/js/propietarios/propietario.js"></script>
<script type="text/javascript" src="../public/js/ut/ut.js"></script>
<script type="text/javascript" src="../public/js/proveedores/proveedores.js"></script>
<script type="text/javascript" src="../public/js/mensualidades/mensualidad.js"></script>
<script type="text/javascript" src="../public/js/apartamentos/apartamento.js"></script>
<script type="text/javascript" src="../public/js/documentos/documento.js"></script>
<script type="text/javascript" src="../public/js/notificacion/notificacion.js"></script>
<script type="text/javascript" src="../public/js/pagos/pagos.js"></script>
<script type="text/javascript" src="../public/js/cuenta/cuenta.js"></script>
<script type="text/javascript" src="../public/js/gastos/gastos.js"></script>
<script type="text/javascript" src="../public/js/mensualidades/generar.js"></script>
<script type="text/javascript" src="../public/js/propietarios/contrato.js"></script>
</body>
</html>