<div class="modal fade" id="editAuditoria">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Auditoria</h4>
            </div>
            <div class="modal-body">
                <form id="formEditAuditoria">
                    <div class="form-group">
                        <input class="form-control" type="text" disabled id="id_auditoria">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" id="new_usuario" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" id="new_nivel" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" id="new_tabla" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" id="new_accion" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" id="new_fecha_auditoria" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>