<div class="modal fade" id="nuevoPropietario">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nuevo propietario</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevaPropietario" action="../controllers/propietarios/addPropietario.php" method="post">
 					<div class="form-group">
                        <input class="form-control" type="text" required name="cedula" placeholder="Cédula" autocomplete="off">
                    </div>
                     <div class="form-group">
                        <input class="form-control" type="text" required name="nombres" placeholder="Nombres" autocomplete="off">
                    </div>						
                     <div class="form-group">
                        <input class="form-control" type="text" required name="apellidos" placeholder="Apellidos" autocomplete="off">
                    </div>	
                     <div class="form-group">
                        <input class="form-control" type="text" required name="telefono" placeholder="Telefono" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" required name="correo" placeholder="Correo" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" id="contrasena" name="contrasena" placeholder="Contraseña" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" required name="notas" placeholder="Notas" autocomplete="off">
                    </div>		
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>