<div class="modal fade" id="editNovedad">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Banco</h4>
            </div>
            <div class="modal-body">
                <form id="formEditNovedad" action="../controllers/novedad/editNovedad.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_novedad" id="id_new_novedad">
                    </div>
                    <div class="form-group">
                        <select name="id_new_usuario_novedad" class="form-control">
                            <option value="">Selecciona un usuario</option>
                            <?php for($i=0; $i<count($usuarios); $i++){ $rs = $usuarios[$i]; ?>
                                <option value="<?php echo $rs['id_usuario']; ?>">
                                    <?php echo $rs['correo']; ?>        
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_descripcion_novedad" id="new_descripcion_novedad" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>