<?php 
    $instanciaAlicuota = new Alicuota();
    $alicuotas = $instanciaAlicuota->getAlicuota();
?>
<div class="modal fade" id="editApartamento">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Apartamento</h4>
            </div>
            <div class="modal-body">
                <form id="formEditApartamento" action="../controllers/apartamentos/editApartamento.php" method="post">
                    <div class="form-group">
                        <!-- <input class="form-control" type="text" disabled id="id_alicuota"> -->
                        <input type="hidden" name="id_new_apartamento" id="id_new_apartamento">
                    </div>
                   <div class="form-group">
                        <select name="new_alicuota_apartamento" id="new_alicuota_apartamento" class="form-control">
                           <option value="0"></option>
                            <?php for($i=0; $i<count($alicuotas); $i++){ $rs = $alicuotas[$i]; ?>
                                <option value="<?php echo $rs['id_alicuota']; ?>">
                                    <?php echo $rs['alicuota']; ?>        
                                </option>
                            <?php } ?>
                        </select>   
                    </div>
                    <div class="form-group">
                        <input class="form-control" name="new_nombre_apartamento" type="text" id="new_nombre_apartamento" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" name="new_saldo_apartamento" type="text" id="new_saldo_apartamento" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>