<?php 
    $instanciaAlicuota = new Alicuota();
    $alicuotas = $instanciaAlicuota->getAlicuota();
?>
<div class="modal fade" id="nuevoApartamento">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nueva Apartamento</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevoApartamento" action="../controllers/apartamentos/addApartamento.php" method="post">
                   <div class="form-group">
                        <select name="alicuota" class="form-control">
                            <option value="">Selecciona una alicuota</option>
                            <?php for($i=0; $i<count($alicuotas); $i++){ $rs = $alicuotas[$i]; ?>
                                <option value="<?php echo $rs['id_alicuota']; ?>">
                                    <?php echo $rs['alicuota']; ?>        
                                </option>
                            <?php } ?>
                        </select>   
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="nombreApartamento" id="nombreApartamento" placeholder="Nombre" autocomplete="off">
                    </div>
                     <div class="form-group">
                        <input class="form-control" type="text" name="saldoApartamento" id="saldoApartamento" placeholder="Saldo" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>