<div class="modal fade" id="editUt">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar UT</h4>
            </div>
            <div class="modal-body">
                <form id="formEditUt" action="../controllers/ut/editUt.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_ut" id="id_new_ut">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_ut" id="new_ut" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_anio_ut" id="new_anio_ut" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>