<div class="modal fade" id="editNotificacion">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Notificacion</h4>
            </div>
            <div class="modal-body">
                <form id="formEditNotificacion" action="../controllers/notificacion/editNotificacion.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_notificacion" id="id_new_notificacion">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_fecha_notificacion" id="new_fecha_notificacion" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_ubicacion_notificacion" id="new_ubicacion_notificacion" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>