		<ul class="nav nav-tabs nav-justified">
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
		    <li role="presentation" class="active"><a href="!#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Entidades Bancarias</a></li>
		   	
		   	<li role="presentation">
				<div class="input-group input-group-lg">
					<input class="form-control" type="text" id="searchBanco" placeholder="Buscar bancos">
				</div>
			</li>
		   	<li role="presentation" class="dropdown"><a href="" class="dropdown-toggle" id="options" data-toggle="dropdown" aria-controls="options-contents" aria-expanded="false">Opciones <span class="caret"></span></a>
				<ul class="dropdown-menu" aria-labelbody="options" id="options-contents">
					<li>
						<a href="#" onclick="nuevoBanco()" title="Crear proyecto">Nuevo banco</a>								
	    			</li>
				</ul>
			</li>
		  </ul>
		  <!-- Tab panes -->
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane active" id="detalle">
	    		<table class="table table-striped" id="tablaBanco">
		    		<tr>
		    			<th>Id</th>
		    			<th>Descripción</th>
		    			<th>Opciones</th>
		    		</tr>
		    		<?php for($i=0; $i<count($bancos); $i++){ $rs = $bancos[$i]; ?>
		    		<tr>
		    			<td><?php echo $rs['id_banco']; ?></td>
		    			<td><?php echo $rs['descripcion']; ?></td>
		    			<td>
		    				<a href="#" onclick="editBanco(this);" ><i class="glyphicon glyphicon-edit"></i></a>
		    				<a href="#" onclick="delBanco(this);" ><i class="glyphicon glyphicon-trash"></i></a>
		    			</td>
		    		</tr> <?php } ?>
		    	</table>
		    </div>
		  </div>