<div class="modal fade" id="editBanco">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Banco</h4>
            </div>
            <div class="modal-body">
                <form id="formEditBanco" action="../controllers/bancos/editBanco.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_banco" id="id_banco">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_descripcion" id="new_descripcion" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>