<div class="modal fade" id="nuevoBanco">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nuevo Banco</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevoBanco" action="../controllers/bancos/addBanco.php" method="post">
                    <div class="form-group">
                        <input class="form-control" name="descripcion" type="text" id="descripcion" required placeholder="Descripción del banco" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>