<div class="modal fade" id="editDocumento">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Documentos</h4>
            </div>
            <div class="modal-body">
                <form id="formEditDocumentos" action="../controllers/documentos/editDocumento.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_documento" id="id_new_documento">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_fecha_doc" id="new_fecha_doc" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_ubicacion_doc" id="new_ubicacion_doc" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>