<div class="modal fade" id="nuevoDocumento">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Nuevo documento</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevoDocumento" action="../controllers/documentos/addDocumento.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="date" name="fecha" required placeholder="Descripción" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="ubicacion" required placeholder="Ubicacion" autocomplete="off">
                    </div>
                
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>