<div class="modal fade" id="editMensualidad">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar Mensualidad</h4>
            </div>
            <div class="modal-body">
                <form id="formEditMensualidad" action="../controllers/mensualidades/editMensualidad.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="id_new_mensualidad" id="id_new_mensualidad">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_mensualidad_descripcion" id="new_mensualidad_descripcion" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_mensualidad_total" id="new_mensualidad_total" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_mensualidad_fecha" id="new_mensualidad_fecha" autocomplete="off">
                    </div>
<!--                     <div class="form-group">
                        <input class="form-control" type="text" name="new_mensualidad_tipo" id="new_mensualidad_tipo" autocomplete="off">
                    </div> -->
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>