		<ul class="nav nav-tabs nav-justified">
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
		    <li role="presentation" class="active"><a href="!#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Detalles alicuotas</a></li>
		   	
		   	<li role="presentation">
				<div class="input-group input-group-lg">
					<input class="form-control" type="text" id="searchAlicuota" placeholder="Buscar alicuotas">
				</div>
			</li>
		   	<li role="presentation" class="dropdown"><a href="" class="dropdown-toggle" id="options" data-toggle="dropdown" aria-controls="options-contents" aria-expanded="false">Opciones <span class="caret"></span></a>
				<ul class="dropdown-menu" aria-labelbody="options" id="options-contents">
					<li>					
						<a href="#" onclick="nuevaAlicuota()" title="Crear proyecto">Nueva alicuota</a>						
	    			</li>
				</ul>
			</li>
		  </ul>
		  <!-- Tab panes -->
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane active" id="detalle">
				<table class="table table-striped" id="tablaAlicuota">
		    		<tr>
		    			<th>Id</th>
		    			<th>Alicouta</th>
		    			<th>Monto</th>
		    			<th>Opciones</th>
		    		</tr>
		    		<?php for($i=0; $i<count($alicuotas); $i++){ $rs = $alicuotas[$i]; ?>
		    		<tr>
		    			<td><?php echo $rs['id_alicuota']; ?></td>
		    			<td><?php echo $rs['alicuota']; ?></td>
		    			<td><?php echo $rs['monto']; ?></td>
		    			<td>
		    				<a href="#" onclick="editAlicuota(this);" ><i class="glyphicon glyphicon-edit"></i></a>
		    				<a href="#" onclick="delAlicuota(this);" ><i class="glyphicon glyphicon-trash"></i></a>
		    			</td>
		    		</tr> <?php } ?>
		    	</table>
		    </div>
		  </div>